name: Draw the progress of life

on:
  push:
    branches: [ check-github-actions ]
  schedule:
    - cron: '0 19 * * *' # Run daily at 4 am (JST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.6]
        chrome-version: ['91.0.4472.101']
        platform: [ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Install dependencies (for linux)
      if: startsWith(matrix.platform, 'ubuntu')
      run: |  
        echo "deb http://us.archive.ubuntu.com/ubuntu/ yakkety universe" | sudo tee -a /etc/apt/sources.list && \
        sudo apt-get update && \
        sudo apt-get install -y \
                cmake gcc g++ ffmpeg x264 libx264-dev build-essential \
                checkinstall cmake pkg-config yasm git gfortran \
                software-properties-common libjasper1 libtiff-dev libavcodec-dev \
                libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev \
                libv4l-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
                libgtk2.0-dev libtbb-dev qt5-default libatlas-base-dev libfaac-dev \
                libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev \
                libopencore-amrnb-dev libopencore-amrwb-dev libavresample-dev \
                v4l-utils libprotobuf-dev protobuf-compiler libgoogle-glog-dev \
                libgflags-dev libgphoto2-dev libeigen3-dev libhdf5-dev doxygen

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Poetry ${{ matrix.poetry-version }}
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
        
    - name: Clone Python-Charmers repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/iwasakishuto/Python-Charmers
        cd ${GITHUB_WORKSPACE}/Python-Charmers
        poetry install
        poetry run python -c "import pycharmers"

    - name: Create a today's progress typing data
      env:
        DISPLAY: ':0'
      run: |
        cd ${GITHUB_WORKSPACE}/Python-Charmers
        poetry run python ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/typing-create.py \
          --out-progress    ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/progress.json \
          --out-code-before ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/code-before.json \
          --out-code-after  ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/code-after.json

    - name: Draw the progress of life
      env:
        DISPLAY: ':0'
      run: |
        # Create a today's typing video.
        cd ${GITHUB_WORKSPACE}/Python-Charmers
        for codec in VP80 X264 THEO
        do poetry run video_of_typing \
            --typing ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/progress.json \
                    ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/code-before.json \
                    ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/code-after.json \
            --video ${GITHUB_WORKSPACE}/videos/dna-base-pc.mp4 \
            --size '[1600, 900]' \
            --fps 25 \
            --codec ${codec} \
            --out ${GITHUB_WORKSPACE}/videos/dna-python-loading.mp4
        done
        # Wait for the created video to be saved.
        sleep 5
        
    - name: Git updates
      run: |
        cd ${GITHUB_WORKSPACE}
        git config --local user.name 'iwasakishuto'
        git config --local user.email 'cabernet.rock@gmail.com'
        git pull origin HEAD
        git add "${GITHUB_WORKSPACE}/videos/dna-python-loading*" \
                ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/code-before.json \
                ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/code-after.json \
                ${GITHUB_WORKSPACE}/.github/workflows-python/dna-lifetime/progress.json
        git commit -m ':dna: Live my life I love.'
        git push origin HEAD:master